Start frontend
Jumaruba/FEUP-PRI pull request #11
Opened 2021-12-19 22:49 UTC by samyuh

How to run: [alternatives]
- `docker-compose` in root
-  `run_docker.sh` in root

Hosts:
- React Server: localhost:3000
- Solr Admin: localhost:8983

2021-12-24 12:30 UTC, Jumaruba requested changes
- It's not recommended to use `COPY . .` in `dockerfile`. On this way, all the project must be build again when a small modification in `package.json` is done. It should be:
```docker
COPY package*.json ./
COPY src/ src/
COPY public/ public/ 
```
If the package*.json is the only thing that has changed in the project, the `docker` will just update it instead of the whole project.  
Also, by doing `COPY . .` the `node_modules` is being added to the `docker`. 

- Not possible to execute the program.   
There're some compilation problems: 

```
Compiled with problems:

ERROR in ./node_modules/@mui/styled-engine/GlobalStyles/GlobalStyles.js 3:0-40

Module not found: Error: Can't resolve '@emotion/react' in '/node_modules/@mui/styled-engine/GlobalStyles'


ERROR in ./node_modules/@mui/styled-engine/StyledEngineProvider/StyledEngineProvider.js 3:0-47

Module not found: Error: Can't resolve '@emotion/react' in '/node_modules/@mui/styled-engine/StyledEngineProvider'


ERROR in ./node_modules/@mui/styled-engine/index.js 6:0-39

Module not found: Error: Can't resolve '@emotion/styled' in '/node_modules/@mui/styled-engine'


ERROR in ./node_modules/@mui/styled-engine/index.js 30:0-62

Module not found: Error: Can't resolve '@emotion/react' in '/node_modules/@mui/styled-engine'


ERROR in ./node_modules/@mui/system/esm/ThemeProvider/ThemeProvider.js 11:27-60

export 'ThemeContext' (imported as 'StyledEngineThemeContext') was not found in '@mui/styled-engine' (possible exports: GlobalStyles, StyledEngineProvider, default)


ERROR in ./node_modules/@mui/system/esm/index.js 1:0-88

export 'css' (reexported as 'css') was not found in '@mui/styled-engine' (possible exports: GlobalStyles, StyledEngineProvider, default)


ERROR in ./node_modules/@mui/system/esm/index.js 1:0-88

export 'keyframes' (reexported as 'keyframes') was not found in '@mui/styled-engine' (possible exports: GlobalStyles, StyledEngineProvider, default)
```

2021-12-24 12:55 UTC, Jumaruba commented on frontend/Dockerfile
> +COPY public/ public/
Added individual `COPY` to avoid adding `node_module` and improve build performance.

2021-12-24 13:10 UTC, Jumaruba approved these changes
The last commits updates the requested changes.

2021-12-24 13:10 UTC, Jumaruba commented on docker-compose.yaml
> +      - solr
Missing volumes to allow live change in the code.

2021-12-26 08:45 UTC, dianaamfr commented
Deprecated warnings:
![image](https://user-images.githubusercontent.com/56595843/147402895-1ef612a6-af8d-49d7-92cc-bf31cac95f85.png)

Fetch error due to CORS policy (so I couldn't test the search system in the frontend):
![image](https://user-images.githubusercontent.com/56595843/147403037-a5a302a6-fc2e-4e9f-a8d2-59aba1564b0a.png)

I think the problem is with Solr.

2021-12-28 15:43 UTC, dianaamfr approved these changes

2021-12-28 15:49 UTC, merged